components:
  schemas:
    RoleAndDocumentResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data: 
          type: object
          properties:
            id:
              type: string
            created_at:
              type: date
            updated_at:
              type: date
            name:
              type: string
            state:
              type: boolean


#! ---------------- ROLES ------------------- !#
#* **************** GET ALL ********************* #
paths:
  /roles:
    get:
      tags: 
        - Role
      summary: "Get all roles"
      
      responses:
        200:
          description: "OK"
          content: 
            application/json: 
              schema:
                $ref: "#/components/schemas/RoleAndDocumentResponse"

#* **************** GET ONE ********************* #
  /role/{id}:
    get:
      tags: 
        - Role
      summary: "get one role with id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "identifier role"
      responses:
        200:
          description: "OK"
          content: 
            application/json: 
              schema:
                $ref: "#/components/schemas/RoleAndDocumentResponse"

#* **************** GET ONE WITH PERSONN ********************* #
  /roleWithPersons/{id}:
    get:
      tags: 
        - Role
      summary: "get one role with their persons"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "identifier role"
          
      responses:
        200:
          description: "OK"
          content: 
            application/json: 
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data: 
                    type: object
                    properties:
                      name:
                        type: string
                      person: 
                        type: object
                        properties:
                          name:
                            type: string
                          lastnames:
                            type: string
                          code: 
                            type: string
                          institutional_mail:
                            type: string

#* **************** CREATE ********************* #
  /role/create:
    post:
      tags: 
        - Role
      summary: "create a new role"
            
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties: 
                name:
                  type: string

      responses:
        201:
          description: "Created"
          content: 
            application/json: 
              schema:
                $ref: "#/components/schemas/RoleAndDocumentResponse"
          
#* **************** DELETE ********************* #
  /role/delete/{id}:
    patch:
      tags: 
        - Role
      summary: "delete one role by id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        204:
          description: "deleted successfully"

#* **************** UPDATE ********************* #
  /role/update/{id}:
    patch:
      tags: 
        - Role
      summary: "update role with id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
        
      requestBody:
      required: true
      content:
        application/json:
          schema: 
            type: object
            properties: 
              name:
                type: string
      responses:
        200:
          description: "update successfully"



#! ---------------- DOCUMENT ------------------- !#
#* **************** GET ALL ********************* #
  /documents:
    get:
      tags: 
        - Document Type
      summary: "Get all documents"
      
      responses:
        200:
          description: "OK"
          content: 
            application/json: 
              schema:
                $ref: "#/components/schemas/RoleAndDocumentResponse"

#* **************** GET ONE ********************* #
  /document/{id}:
    get:
      tags: 
        - Document Type
      summary: "get one document with id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "identifier document"
      responses:
        200:
          description: "OK"
          content: 
            application/json: 
              schema:
                $ref: "#/components/schemas/RoleAndDocumentResponse"

#* **************** GET ONE WITH PERSONN ********************* #
  /documentWithPersons/{id}:
    get:
      tags: 
        - Document Type
      summary: "get one document with their persons"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "identifier document"
          
      responses:
        200:
          description: "OK"
          content: 
            application/json: 
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data: 
                    type: object
                    properties:
                      name:
                        type: string
                      person: 
                        type: object
                        properties:
                          name:
                            type: string
                          lastnames:
                            type: string
                          code: 
                            type: string
                          institutional_mail:
                            type: string

#* **************** CREATE ********************* #
  /document/create:
    post:
      tags: 
        - Document Type
      summary: "create a new document type"
            
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties: 
                name:
                  type: string

      responses:
        201:
          description: "Created"
          content: 
            application/json: 
              schema:
                $ref: "#/components/schemas/RoleAndDocumentResponse"
          
#* **************** DELETE ********************* #
  /document/delete/{id}:
    patch:
      tags: 
        - Document Type
      summary: "delete one document by id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        204:
          description: "deleted successfully"

#* **************** UPDATE ********************* #
  /documentType/update/{id}:
    patch:
      tags: 
        - Document Type
      summary: "update document with id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
        
      requestBody:
      required: true
      content:
        application/json:
          schema: 
            type: object
            properties: 
              name:
                type: string
      responses:
        200:
          description: "update successfully"